```{r global_options, include=FALSE}
library(magrittr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(reshape)
library(psych)
```
```{r}
PB1 <- merge_all(list(read.csv(file='H2N2PB1.tidy.csv', head=TRUE, sep='\t'), 
                      read.csv(file='H1N1PB1.tidy.csv', head=TRUE, sep='\t'), 
                      read.csv(file='H3N2PB1.tidy.csv', head=TRUE, sep='\t')), 
                 all.x=TRUE, all.y=TRUE)
codonvalues <- read.csv(file='codonvalues.csv', head=TRUE, sep='\t')
rtPB1 <- PB1 %>% left_join(select(codonvalues, codon, CAI, CAImax))
```

*CAI*
```{r}
rtPB1 %>% 
  filter(codon != 'ATG', codon!='TGG', codon!='TAA', codon!='TAG', codon!='TGA') %>%
  group_by(sero, strain) %>% 
  mutate(cods = sum(numcodon), initC = CAI ** numcodon, initCm = CAImax ** numcodon) %>% 
  summarize(coryear=mean(coryear),
            score=((prod(initC))**mean(1/cods))/((prod(initCm))**mean(1/cods))) %>%
  ggplot(aes(x=coryear, y=score, color=sero)) + geom_point() 
```

Mucking about with ylim
```{r}
rtPB1 %>% 
  filter(codon != 'ATG', codon!='TGG', codon!='TAA', codon!='TAG', codon!='TGA') %>%
  group_by(sero, strain) %>% 
  mutate(cods = sum(numcodon), initC = CAI ** numcodon, initCm = CAImax ** numcodon) %>% 
  summarize(coryear=mean(coryear),
            score=((prod(initC))**mean(1/cods))/((prod(initCm))**mean(1/cods))) %>%
  ggplot(aes(x=coryear, y=score, color=sero)) + geom_point() + ylim(.54, .58)
```
