```{r global_options, include=FALSE}
library(magrittr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(reshape)
library(MASS)
library(scales)
library(BSDA)
```

*Growth Curves*
```{r}
growthcurves <- read.csv(file='growthcurves.csv', head=TRUE, sep=',')

curve1<-growthcurves %>% filter(group==1) %>% 
  ggplot(aes(x=Time.hours., y=titer.pfu.mL., shape=strain, color=strain)) + 
  geom_point(size=3) + geom_line(size=1) + 
  geom_errorbar(aes(ymin=titer.pfu.mL.-sd, ymax=titer.pfu.mL.+sd, width=1), color='black', size=.3) + 
  facet_wrap(~treatment, ncol=2) +
  scale_y_log10('Titer (pfu/mL)', breaks = trans_breaks("log10", function(x) 10^x),
                   labels = trans_format("log10", math_format(10^.x))) + 
  scale_x_continuous('Time (hours)') +
  theme(legend.position="bottom",legend.text=element_text(size=14), legend.title=element_blank()) +
  theme(strip.background = element_rect(fill = "white", size = 1, linetype=1)) +
  theme(strip.text.x = element_text(size = 12, face="bold")) +
  theme(axis.title=element_text(size=14, face='bold'))
#t-test for final timepoint IFN-treatment
tsum.test(320000, s.x=89000, n.x=3, mean.y=2200300, s.y=890000, n.y=3, alternative = "less", mu = 0, var.equal = FALSE, conf.level = 0.95)
#p=.03292





curve2<-growthcurves %>% filter(group==2) %>% 
  ggplot(aes(x=Time.hours., y=titer.pfu.mL., shape=strain, color=strain)) + 
  geom_point(size=3) + geom_line(size=1) + 
  geom_errorbar(aes(ymin=titer.pfu.mL.-sd, ymax=titer.pfu.mL.+sd, width=1), color='black', size=.3) + 
    facet_wrap(~treatment, ncol=2) +
  scale_y_log10('Titer (pfu/mL)', breaks = trans_breaks("log10", function(x) 10^x),
                   labels = trans_format("log10", math_format(10^.x))) + 
  scale_x_continuous('Time (hours)') +
  theme(legend.position="bottom",legend.text=element_text(size=14), legend.title=element_blank()) +
  theme(strip.background = element_rect(fill = "white", size = 1, linetype=1)) +
  theme(strip.text.x = element_text(size = 12, face="bold")) +
  theme(axis.title=element_text(size=14, face='bold'))
#t-test for final timepoint IFN-treatment
tsum.test(320000, s.x=80000, n.x=3, mean.y=2200300, s.y=320000, n.y=3, alternative = "less", mu = 0, var.equal = FALSE, conf.level = 0.95)
#p=.003378





curve3<-growthcurves %>% filter(group==3) %>% 
  ggplot(aes(x=Time.hours., y=titer.pfu.mL., shape=strain, color=strain)) +  
  scale_color_manual(values=c("darkorchid1", "#66CCCC"))+
  geom_point(size=3) + geom_line(size=1) + 
  geom_errorbar(aes(ymin=titer.pfu.mL.-sd, ymax=titer.pfu.mL.+sd, width=1), color='black', size=.3) + 
    facet_wrap(~treatment, ncol=2) +
  scale_y_log10('Titer (pfu/mL)', breaks = trans_breaks("log10", function(x) 10^x),
                   labels = trans_format("log10", math_format(10^.x))) + 
  scale_x_continuous('Time (hours)') +
  theme(legend.position="bottom",legend.text=element_text(size=14), legend.title=element_blank()) +
  theme(strip.background = element_rect(fill = "white", size = 1, linetype=1)) +
  theme(strip.text.x = element_text(size = 12, face="bold")) +
  theme(axis.title=element_text(size=14, face='bold'))
#t-test for final timepoint IFN-treatment
tsum.test(15000, s.x=2000, n.x=3, mean.y=50000, s.y=10000, n.y=3, alternative = "less", mu = 0, var.equal = FALSE, conf.level = 0.95)
#p=.0113



ggdraw()+
  draw_plot(curve1, 0, .5, .5, .5)+
  draw_plot(curve2, .5, .5, .5, .5)+
  draw_plot(curve3, .5, 0, .5, .5)
```

```{r}
newcurves <- read.csv(file='newcurves.csv', head=TRUE)

newcurves %>% 
  ggplot(aes(x=strain, y=titer.pfu.mL., fill=treatment)) +
  geom_bar(stat="identity", position=position_dodge()) + 
  geom_errorbar(aes(ymin=titer.pfu.mL.-sd, ymax=titer.pfu.mL.+sd, width=.9), color='black', size=.3, position=position_dodge()) +
  scale_y_log10('Titer (pfu/mL)', breaks = trans_breaks("log10", function(x) 10^x),
                   labels = trans_format("log10", math_format(10^.x)))
```



Fold change on new growth
```{r}
foldchanges <- read.csv(file='foldchanges.csv', head=TRUE)

foldchanges$Virus <- factor(sigraw$strain, levels = c('ud', 'sig1', 'sig2', 'sigall'))


#A549
foldchanges %>% filter(cell=='a549') %>%
  ggplot(aes(x=Virus, y=Fold.change, fill=Virus)) +
  geom_bar(stat="identity", position=position_dodge()) + 
  scale_x_discrete(#position = "top", 
                   limits = c('ud', 'sig1', 'sig2', 'sigall'
                              ), position = "top") +
  geom_errorbar(aes(ymin=Fold.change-sd/sqrt(3), ymax=Fold.change+sd/sqrt(3), width=.5), color='black', size=.3, position=position_dodge()) +
  theme(legend.position="none") +
  ylab('Fold Viral Attenuation Between IFN and Untreated') + 
  scale_y_reverse(lim=c(20, 0), expand = c(0,0)) +
  #scale_y_continuous(lim=c(0,20), expand = c(0,0)) +
  guides(fill = FALSE)


#t-test for fold inhibition sig1 construct vs. wt
tsum.test(16.973984, s.x=3.3139883, n.x=3, mean.y=3.388356, s.y=0.6044129, n.y=3, alternative = "greater", mu = 0, var.equal = FALSE, conf.level = 0.95)
#p=.008361

#t-test for fold inhibition sig2 construct vs. wt
tsum.test(16.973984, s.x=3.3139883, n.x=3, mean.y=4.571065, s.y=0.8246825, n.y=3, alternative = "greater", mu = 0, var.equal = FALSE, conf.level = 0.95)
#p=.009078

#t-test for fold inhibition sigall construct vs. wt
tsum.test(16.973984, s.x=3.3139883, n.x=3, mean.y=4.795833, s.y=1.0428577, n.y=3, alternative = "greater", mu = 0, var.equal = FALSE, conf.level = 0.95)
#p=.008341


```



```{r}
sigraw <- read.csv(file='newcurves.csv', head=TRUE)
sigraw$treatment <- factor(sigraw$treatment, levels = c('untreated', 'IFN treated'))
sigraw$strain <- factor(sigraw$strain, levels = c('ud', 'sig1', 'sig2', 'sigall'))

sigraw %>%
  ggplot(aes(x=treatment, y=titer.pfu.mL., fill=treatment)) +
  geom_point(aes(color=treatment), position=position_dodge(width=0.9), size=5) +
  geom_errorbar(aes(ymin=titer.pfu.mL.-sd/sqrt(3), ymax=titer.pfu.mL.+sd/sqrt(3), width=.5), color='black', position=position_dodge(.9)) +
  ylab('Titer at 36 hours (pfu/mL)') + 
  xlab('Treatment condition') +
  scale_y_log10(lim=c(10000, 50000000), breaks=c(1000, 10000,100000,1000000,10000000,100000000)) +
  facet_grid(~strain, scales='free_x') + 
  panel_border() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.border = element_rect(color = "black", fill = NA, size = 1), 
        strip.background = element_rect(color = "black"),
        legend.position="none")


```

```{r}
rtaifold <- read.csv(file='foldchange-vs-rtai.csv', head=TRUE)

foldcor<-cor(log2(rtaifold$Fold.change), rtaifold$rtAI)

corplot<-rtaifold %>%
  ggplot(aes(x=rtAI, y=log2(Fold.change), label=virus)) +
  geom_point()+
  geom_label() +
  geom_smooth(aes(x=rtAI, y=log2(Fold.change)), method='lm', color='darkgrey', size=0.5)

ggdraw(corplot)+draw_label(expression('R = -0.690'), x=.3, y=.25, vjust = 1, hjust = 1, size = 14, fontface = 'bold')







foldcor<-cor((rtaifold$Fold.change), rtaifold$rtAI)

corplot<-rtaifold %>%
  ggplot(aes(x=rtAI, y=(Fold.change), label=virus)) +
  geom_point()+
  geom_label() +
  geom_smooth(aes(x=rtAI, y=(Fold.change)), method='lm', color='darkgrey', size=0.5)

ggdraw(corplot)+draw_label(expression('R = -0.715'), x=.3, y=.25, vjust = 1, hjust = 1, size = 14, fontface = 'bold')

```