```{r global_options, include=FALSE}
library(magrittr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(reshape)
library(MASS)
library(scales)
```

*Growth Curves*
```{r}
growthcurves <- read.csv(file='growthcurves.csv', head=TRUE, sep='\t')

curve1<-growthcurves %>% filter(group==1) %>% 
  ggplot(aes(x=Time.hours., y=titer.pfu.mL., shape=strain, color=strain)) + 
  geom_point(size=3) + geom_line(size=1) + 
  geom_errorbar(aes(ymin=titer.pfu.mL.-sd, ymax=titer.pfu.mL.+sd, width=1), color='black', size=.3) + 
  facet_wrap(~treatment, ncol=2) +
  scale_y_log10('Titer (pfu/mL)', breaks = trans_breaks("log10", function(x) 10^x),
                   labels = trans_format("log10", math_format(10^.x))) + 
  scale_x_continuous('Time (hours)') +
  theme(legend.position="bottom",legend.text=element_text(size=14), legend.title=element_blank()) +
  theme(strip.background = element_rect(fill = "white", size = 1, linetype=1)) +
  theme(strip.text.x = element_text(size = 12, face="bold")) +
  theme(axis.title=element_text(size=14, face='bold'))

curve2<-growthcurves %>% filter(group==2) %>% 
  ggplot(aes(x=Time.hours., y=titer.pfu.mL., shape=strain, color=strain)) + 
  geom_point(size=3) + geom_line(size=1) + 
  geom_errorbar(aes(ymin=titer.pfu.mL.-sd, ymax=titer.pfu.mL.+sd, width=1), color='black', size=.3) + 
    facet_wrap(~treatment, ncol=2) +
  scale_y_log10('Titer (pfu/mL)', breaks = trans_breaks("log10", function(x) 10^x),
                   labels = trans_format("log10", math_format(10^.x))) + 
  scale_x_continuous('Time (hours)') +
  theme(legend.position="bottom",legend.text=element_text(size=14), legend.title=element_blank()) +
  theme(strip.background = element_rect(fill = "white", size = 1, linetype=1)) +
  theme(strip.text.x = element_text(size = 12, face="bold")) +
  theme(axis.title=element_text(size=14, face='bold'))

curve3<-growthcurves %>% filter(group==3) %>% 
  ggplot(aes(x=Time.hours., y=titer.pfu.mL., shape=strain, color=strain)) +  
  scale_color_manual(values=c("darkorchid1", "#66CCCC"))+
  geom_point(size=3) + geom_line(size=1) + 
  scale_shape_manual(values=c(15, 17))+
  geom_errorbar(aes(ymin=titer.pfu.mL.-sd, ymax=titer.pfu.mL.+sd, width=1), color='black', size=.3) + 
    facet_wrap(~treatment, ncol=2) +
  scale_y_log10('Titer (pfu/mL)', breaks = trans_breaks("log10", function(x) 10^x),
                   labels = trans_format("log10", math_format(10^.x))) + 
  scale_x_continuous('Time (hours)') +
  theme(legend.position="bottom",legend.text=element_text(size=14), legend.title=element_blank()) +
  theme(strip.background = element_rect(fill = "white", size = 1, linetype=1)) +
  theme(strip.text.x = element_text(size = 12, face="bold")) +
  theme(axis.title=element_text(size=14, face='bold'))

ggdraw()+
  draw_plot(curve1, 0, .5, .5, .5)+
  draw_plot(curve2, .5, .5, .5, .5)+
  draw_plot(curve3, .5, 0, .5, .5)
```